### ISSUE TITLE
Initial Appearance of Webpage

### ISSUE THREAD

**Issue by mschore** [akserg/learning_bootstrap4_angular2#1]
I am trying to follow the book and this new set of code. However, when I open the ecommerce-seed files I am seeing odd behavior in the page. The navbar doesn't display, the cards are all over the place. Can someone point me to what might be going on. I am including a picture of the results I am seeing.
![ashampoo_snap_2017 06 12_17h11m26s_001_](https://user-images.githubusercontent.com/2125862/27055847-c6e91aaa-4f93-11e7-9cf4-fbb726c6df1b.png)

**Comment by akserg** [comment]
Hi @mschore 
Can you share more details like the chapter number, your environment, how can I reproduce it?

**Comment by mschore** [comment]
Sergey

I am using Windows 10 with the normal load of software. Here is my output from ng –version.

    _                      _                 ____ _     ___

   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|

  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |

/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |

/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|

               |___/

@angular/cli: 1.1.1

node: 6.11.0

os: win32 x64

@angular/common: 2.4.10

@angular/compiler: 2.4.10

@angular/core: 2.4.10

@angular/forms: 2.4.10

@angular/http: 2.4.10

@angular/platform-browser: 2.4.10

@angular/platform-browser-dynamic: 2.4.10

@angular/router: 3.4.10

@angular/upgrade: 2.4.10

 

I have updated Bootstrap to the latest 3.3.7 version.  I am using VS Code for development. Any other information I can provide?

Regards

Michael Schore

**Comment by mschore** [comment]
Sergey

Almost forgot. This is happening with the ecommerce-seed files for Chapter 3, 4 and 5.

Regards

**Comment by akserg** [comment]
Hi Michael,

> I have updated Bootstrap to the latest 3.3.7 version.

I don't understand your point about version 3. The book and all code for Bootstrap 4 and Angular 2 (version 4).

**Comment by akserg** [comment]
Another question - do you use this repo or the one from Packt. The repo on Packt seems out of date. Please use this one.

**Comment by mschore** [comment]
I am currently using this one. I also just updated the Bootstrap in the third version of Chapter 5 and am getting the same result I showed before. 
Forgot to include this information. When I first open one of the ecommerce-seed files (Ch 3, 4 or 5) I run npm install followed by a npm run start. I get the following (which may be a clue as to what is happening):
> tsc && concurrently "npm run tsc:w" "npm run lite"

error TS2688: Cannot find type definition file for 'hammerjs'.
error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'node'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ecommerce-seed@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ecommerce-seed@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2017-06-13T12_43_12_909Z-debug.log

**Comment by akserg** [comment]
I see the same error a week ago. The npm, for unknown reasons, do not install the following packages on Windows:

![image](https://user-images.githubusercontent.com/1400409/27116074-521ee3de-50cf-11e7-9108-4f66cdc0f2b6.png)

Please send the log file `C:\Users\Mike\AppData\Roaming\npm-cache_logs\2017-06-13T12_43_12_909Z-debug.log`. I would like to investigate what is the problem.

**Comment by mschore** [comment]
I have attached the requested log file. I have been concerned that my dev system is now misconfigured with various versions of the needed software. I guess this is the cost of working with open source software.

[2017-06-13T12_43_12_909Z-debug.zip](https://github.com/akserg/learning_bootstrap4_angular2/files/1074950/2017-06-13T12_43_12_909Z-debug.zip)

**Comment by mschore** [comment]
By the way, I just went to the ecommerce-seed code start up from Chapter 2 and tried to do the install. I am seeing this after the install runs. Looks like it isn't installing the Typescript connections.
![image](https://user-images.githubusercontent.com/2125862/27139377-d9e4b9da-50f0-11e7-965b-17e3fe37989e.png)
